# Site
title:              GrobleLaw
bio:                'Benefit from our experience. \n 18 West Stow Road, Marlton, NJ\n 08053, USA \n(856) 817-1242 (phone) \n(856) 817-1243 (fax) \nwilliam@groblelaw.com'
description:        "The Law Offices of William Groble are ready to assist you "
reading_time:       true
words_per_minute:   200
logo:               'assets/img/lawlogo.png'
background:         'assets/img/lawoffice.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                "https://groblelaw.github.io"

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   groblelaw

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:              william@groblelaw.com
# twitter:            username
# facebook:           username
github-url:         groblelaw
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           groblelaw
#xing:              username
# instagram:          username
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
# steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
